
stories = [
    {
        "_id": "1",
        "name": "Krunal M",
        "image": "/images/gojo.jpg",
    },
    {
        "_id": "2",
        "name": "Meet C",
        "image": "/images/gojo.jpg",
    },
    {
        "_id": "3",
        "name": "Shiv R",
        "image": "/images/gojo.jpg",
    },
    {
        "_id": "4",
        "name": "Helly C",
        "image": "/images/gojo.jpg",
    },
    {
        "_id": "5",
        "name": "Helly C",
        "image": "/images/gojo.jpg",
    },
    {
        "_id": "6",
        "name": "Helly C",
        "image": "/images/gojo.jpg",
    },

    {
        "_id": "7",
        "name": "Helly C",
        "image": "/images/gojo.jpg",
    }, {
        "_id": "8",
        "name": "Helly C",
        "image": "/images/gojo.jpg",
    }, {
        "_id": "9",
        "name": "Helly C",
        "image": "/images/gojo.jpg",
    },
    {
        "_id": "10",
        "name": "Helly C",
        "image": "/images/gojo.jpg",
    }, {
        "_id": "11",
        "name": "Helly C",
        "image": "/images/gojo.jpg",
    },
]

posts = [
    {
        "_id": "1",
        "name": "Meet Chauhan",
        "userId": "6",
        "profilePic": "/images/sky.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/pp.jpg",
    },
    {
        "_id": "2",
        "name": "Priyansh Rohit",
        "userId": "8",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/gojo.jpg",
    },
    {
        "_id": "3",
        "name": "Vivek Makwana",
        "userId": "2",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/bench_drawing.jpg",
    },
    {
        "_id": "4",
        "name": "Vivek Makwana",
        "userId": "2",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/vinayaka.jpg",
    },
    {
        "_id": "5",
        "name": "Vivek Makwana",
        "userId": "2",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/bhes.jpg",
    },
    {
        "_id": "6",
        "name": "Vivek Makwana",
        "userId": "2",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/chakli.jpg",
    },
    {
        "_id": "7",
        "name": "Digvijay",
        "userId": "3",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/cow.jpg",
    },
    {
        "_id": "8",
        "name": "Digvijay",
        "userId": "3",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/firecracker.jpg",
    },
    {
        "_id": "9",
        "name": "Digvijay",
        "userId": "3",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/ice_cola.jpg",
    },
    {
        "_id": "10",
        "name": "Digvijay",
        "userId": "3",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/icecream.jpg",
    },
    {
        "_id": "11",
        "name": "Yug Makwana",
        "userId": "4",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/icecream_watch.jpg",
    },
    {
        "_id": "12",
        "name": "Yug Makwana",
        "userId": "4",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/khetar.jpg",
    },
    {
        "_id": "13",
        "name": "Yug Makwana",
        "userId": "4",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/khetar_sunset.jpg",
    },
    {
        "_id": "14",
        "name": "Yug Makwana",
        "userId": "4",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/khetar2.jpg",
    },
    {
        "_id": "15",
        "name": "Miten",
        "userId": "5",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/khetar3.jpg",
    },
    {
        "_id": "16",
        "name": "Miten",
        "userId": "5",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/mango.jpg",
    },
    {
        "_id": "17",
        "name": "Krunal Makwana",
        "userId": "1",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/me_river.jpg",
    },
    {
        "_id": "18",
        "name": "Krunal Makwana",
        "userId": "1",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/me_sunset.jpg",
    },
    {
        "_id": "19",
        "name": "Krunal Makwana",
        "userId": "1",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/me_fool.jpg",
    },
    {
        "_id": "20",
        "name": "Meet Chauhan",
        "userId": "6",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/night_river.jpg",
    },
    {
        "_id": "21",
        "name": "Meet Chauhan",
        "userId": "6",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/nowayhome.jpg",
    },
    {
        "_id": "22",
        "name": "Meet Chauhan",
        "userId": "6",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/sky.jpg",
    },
    {
        "_id": "23",
        "name": "Het Patel",
        "userId": "7",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/sunset.jpg",
    },
    {
        "_id": "24",
        "name": "Het Patel",
        "userId": "7",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/water.jpg",
    },
    {
        "_id": "25",
        "name": "Krunal Makwana",
        "userId": "1",
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/water_shadow.jpg",
    },
    {
        "_id": "26",
        "name": "Het Patel",
        "userId": 7,
        "profilePic": "/images/gojo.jpg",
        "desc": "Lorem ipsum dolor sit amet consectetur adipisicing",
        "image": "/images/yellow_fool.jpg",
    },
    
    
]