# Generated by Django 4.1.6 on 2023-02-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('userId', models.CharField(max_length=10)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
