# Generated by Django 4.1.6 on 2023-02-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='profilePic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
