# Generated by Django 4.1.6 on 2023-02-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_post_image_alter_post_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
