# Generated by Django 4.1.6 on 2023-02-14 18:56

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_post_created_at_remove_post_no_of_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to=base.models.path_and_rename)),
            ],
        ),
    ]
