# Generated by Django 4.1.6 on 2023-02-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_stories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stories',
            new_name='Story',
        ),
        migrations.AlterField(
            model_name='post',
            name='userId',
            field=models.CharField(max_length=10),
        ),
    ]
