# Generated by Django 4.1.6 on 2023-02-15 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_story_image_remove_story_name_story_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.post'),
        ),
    ]
