# Generated by Django 4.1.6 on 2023-02-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_postcomments_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='comment',
            new_name='commnet_text',
        ),
    ]
